version: '3'
services:
  decantador:
    container_name: decantador
    image: rlproto/picture:picture-v1.5  # Use the existing 'picture' image from Docker Hub
    network_mode: bridge
    devices:
      - "/dev/video0:/dev/video0"
    restart: unless-stopped
    volumes:
      #- decantador:/data
      - /var/lib/docker/volumes/picture_decantador:/app/data
    environment:
      OPC_SERVER_URL: "opc.tcp://10.15.160.149:49312"
      TAG_NAME: "ns=2;s=BRASSAGEM.PLC1.WHIRLPOOL.SORBA.PHASE"
      #TAG_NAME: "ns=2;s=SODA_TEMPLATE.FILTRACAO.RASP_PASSO"
      PRODUCT_TAG_NAME: "ns=2;s=BRASSAGEM.PLC1.WHIRLPOOL.SORBA.PROGNO"
      CAMERA_INDEX: "0"
      EQUIPMENT: "DECANTADOR"
      VALID_STEPS: "1;0;1,2;0;1,3;0;1,4;0;1,5;0;1,6;0;1,12;30;2"
      NUMBER_OF_PICTURES: "10"
      
      #100;0;1
      #100 -> PASSO
      #0 -> DELAY OU INTERVALO
      #1 > ESTRATÉGIA

      #ESTRATÉGIA:
      #1 -> ENTRADA DO PASSO
      #2 -> SAÍDA DO PASSO
      #3 -> INTERVALO DE TEMPO DURANTE O PASSO

      #1 -> ENTRADA DO PASSO COM DELAY

    command: ["python", "app.py"]
volumes:
  decantador:
