version: '3'
services:
  decantador-image-capture:
    build: .
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - decantador:/data
    environment:
      OPC_SERVER_URL: "opc.tcp://10.18.12.185:49324"
      TAG_NAME: "ns=2;s=COLETA_DADOS.Device1.TRP_GRAOS.TESTE_1"
      PRODUCT_TAG_NAME: "ns=2;s=COLETA_DADOS.Device1.TRP_GRAOS.TESTE_2"
      CAMERA_INDEX: "0"
      EQUIPMENT: "DECANTADOR"
      VALID_STEPS: "100;0;1,200;0;2,300;5;1,400;10;3"
      NUMBER_OF_PICTURES: "1"

volumes:
  decantador:

    #devices:
      #- "/dev/video0:/dev/video0"  # Grants the container access to the video device