version: '3'
services:
  decantador:
    name: decantador
    image: rlproto/picture:picture-v1.0  # Use the existing 'picture' image from Docker Hub
    network_mode: bridge
    devices:
      - "/dev/video0:/dev/video0"
    restart: unless-stopped
    volumes:
      - decantador:/data
    environment:
      OPC_SERVER_URL: "opc.tcp://10.15.160.149:49312"
      TAG_NAME: "ns=2;s=BRASSAGEM.PLC1.WHIRLPOOL.SORBA.PHASE"
      PRODUCT_TAG_NAME: "ns=2;s=BRASSAGEM.PLC1.WHIRLPOOL.SORBA.PROGNO"
      CAMERA_INDEX: "0"
      EQUIPMENT: "DECANTADOR"
      VALID_STEPS: "2;0;1,5;0;1,13;0;1"
      NUMBER_OF_PICTURES: "5"
      

      #100;0;1
      #100 -> PASSO
      #0 -> DELAY OU INTERVALO
      #1 > ESTRATÉGIA

      #STRATÉGIA:
      #1 -> ENTRADA DO PASSO
      #2 -> SAÍDA DO PASSO
      #3 -> INTERVALOR DE TEMPO DURANTE O PASSO

      #1 -> ENTRADA DO PASSO COM DELAY

volumes:
  decantador:

    #devices:
      #"/dev/video0:/dev/video0"  # Grants the container access to the video device