version: '3'
services:
  cozinhador:
    container_name: cozinhador
    image: rlproto/picture:picture-v1.6  # Use the existing 'picture' image from Docker Hub
    network_mode: bridge
    devices:
      - "/dev/video0:/dev/video0"
    restart: unless-stopped
    volumes:
      #- cozinhador:/data
      - /var/lib/docker/volumes/picture_cozinhador:/app/data
    environment:
      OPC_SERVER_URL: "opc.tcp://10.15.160.149:49312"
      #TAG_NAME: "ns=2;s=BRASSAGEM.PLC1.COZINHADOR_MOSTO.SORBA.PHASE"
      TAG_NAME: "ns=2;s=SODA_TEMPLATE.FILTRACAO.RASP_PASSO"
      PRODUCT_TAG_NAME: "ns=2;s=BRASSAGEM.PLC1.COZINHADOR_MOSTO.SORBA.PROGNO"
      CAMERA_INDEX: "0"
      EQUIPMENT: "cozinhador"
      VALID_STEPS: "2;15;3,3;0;1,5;120;3,6;180;3,8;15;3,9;0;1,9;0;2"
      #VALID_STEPS: "2;15;3,3;15;3,5;120;3,6;180;3,8;15;3,9;0;1,9;0;2"
      NUMBER_OF_PICTURES: "2"
      
      #VALID_STEPS: "1;0;1,2;0;1,3;0;1,4;0;1,5;0;1,6;0;1,7;0;1,8;0;1,9;0;1"
      #NUMBER_OF_PICTURES: "5"
      
      #100;0;1
      #100 -> PASSO
      #0 -> DELAY OU INTERVALO
      #1 > ESTRATÉGIA

      #ESTRATÉGIA:
      #1 -> ENTRADA DO PASSO
      #2 -> SAÍDA DO PASSO
      #3 -> INTERVALO DE TEMPO DURANTE O PASSO

      #1 -> ENTRADA DO PASSO COM DELAY

    command: ["python", "app.py"]
volumes:
  cozinhador: